site_name: Ali Bashir's Documents
repo_url: https://github.com/ali-basher/My-Documents
site_url: https://ali-basher.github.io/My-Documents/


theme:
  name: material
  palette:
     # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: indigo
      accent:  green
  features:
    - navigation.footer
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  icon:
    admonition:
      note: simple/linux
  font:
    text: Roboto
    code: Fira Code
  logo: assets/code.png
  favicon: assets/linux.png

# extensions

markdown_extensions:
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - abbr
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes
  - toc:
      permalink: true
      title: On this page
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# navigation bar 

nav:
  - Home: index.md
  - Java:
    - Java/Test.md

# plugins


plugins:
  - search
  - glightbox

extra:
  social:
    - icon: material/email
      link: mailto:alibasher2000.16.11@gmail.com
    - icon: fontawesome/brands/mastodon 
      link: https://mastodon.social/@ali_basher
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ll1onell
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ali-basher/
    - icon: fontawesome/brands/github
      link: https://github.com/alibasheras1234
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@alibasher1200
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/intjt2
  version:
    provider: mike

copyright: Copyright &copy; 2023 - 2023 Ali Bashir
